// 全局
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// 首页
export const GET_HOME_TODAY_DATA = 'GET_HOME_TODAY_DATA';
export const GET_HOME_ORDER_STATISTIC = 'GET_HOME_ORDER_STATISTIC';
export const GET_HOME_PAY_ORDER_STATISTIC = 'GET_HOME_PAY_ORDER_STATISTIC';

// 课程模块
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_LIST = 'GET_COURSE_LIST';
